name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Determine semantic version
        id: version
        uses: PaulHatch/semantic-version@v4.0.3
        with:
          major_pattern: "major:"
          minor_pattern: "feat:"
          format: "${major}.${minor}.${patch}-prerelease${increment}"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          NEW_TAG=${{ steps.version.outputs.version }}
          docker build \
            --build-arg NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=${{ secrets.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY }} \
            --build-arg NEXT_PUBLIC_BACKEND=${{ secrets.NEXT_PUBLIC_BACKEND }} \
            --build-arg APP_VERSION=${NEW_TAG} \
            -t ${{ secrets.DOCKER_REPOSITORY }}:${NEW_TAG} \
            -t ${{ secrets.DOCKER_REPOSITORY }}:latest \
            .

      - name: Push Docker image
        run: |
          NEW_TAG=${{ steps.version.outputs.version }}
          docker push ${{ secrets.DOCKER_REPOSITORY }}:${NEW_TAG}
          docker push ${{ secrets.DOCKER_REPOSITORY }}:latest
